print("Noun?")
input1 = input()
print("Verb?")
input2 = input()
print("Advjective?")
input3 = input()
print("Adverb?")
input4 = input()
print('Do you %s your %s %s %s ?' % (input1,input2,input3,input4))
